# Generated by Django 3.2.25 on 2024-03-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdetails',
            options={'verbose_name': 'memberdetails', 'verbose_name_plural': 'memberdetails'},
        ),
    ]
