# Generated by Django 3.1 on 2024-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20240315_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='blankplace',
            field=models.CharField(default='tst', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='waara',
            field=models.CharField(default='sdfasf', max_length=50),
            preserve_default=False,
        ),
    ]
