# Generated by Django 3.1 on 2024-03-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20240328_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='waaradata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('waara', models.CharField(max_length=50)),
                ('blankplace', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'waaradatas',
                'verbose_name_plural': 'waaradata',
            },
        ),
    ]
